// <auto-generated />
using System;
using MaxPrimeNumber.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MaxPrimeNumber.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230910195436_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MaxPrimeNumber.Entities.EnteredNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnteredNumberUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("EnteredNumbers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxPrimeNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EnteredNumbers");
                });

            modelBuilder.Entity("MaxPrimeNumber.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
